### PR TITLE
Multistage build for smaller image

### PR DESCRIPTION
**Pull request by tympom**

### CODE REVIEW

**Comment by cloudrac3r** [comment]
Please write a description explaining what problem this solves and why it is useful. If it really does create a smaller image, please provide numbers as evidence.

**Comment by tympom** [comment]
Multi-stage build used as described in https://docs.docker.com/develop/develop-images/multistage-build/ to optimize the image size.

With multi-stage final image contains only the base node image and the bibliogram application withouth git, python3, make and g++ packages with their dependencies - which are needed for instllation but not (at least in my tests) necessary to run bibliogram. The final image is ~291MB vs ~591MB originally.

The gain is not spectacular - only Docker image size but still :)

**Comment by cloudrac3r** [comment]
Huh, that's neat. Thanks for the information!

**Comment by tympom** [comment]
Great project by the way! :)

**Pull request merged**
