### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by cloudrac3r** [comment]
Looks good, thank you!

GitHub is no longer the upstream of Bibliogram, so I'll have to apply your changes manually rather than using the pull request merge feature.

The word "sourcehut" is stylised as all lowercase. I'll change that myself when I apply these changes.

Currently there are still some parts of Bibliogram that cannot be translated, most notably the settings page. When I make it possible to translate these parts, would you like me to contact you so that you can write more translations?

**Comment by TotalCaesar659** [comment]
Yes, you can write here in this thread and I'll get notification.

**Comment by cloudrac3r** [comment]
I have actually just created a mailing list to notify people when there are new things available to translate. You can subscribe to this mailing list: https://lists.sr.ht/~cadence/bibliogram-translate . When new things are available to translate, I will make a descriptive post on that list showing what's new so that you can translate it.

If you're interested in keeping this translation up to date, please subscribe.

**Comment by TotalCaesar659** [comment]
Thanks, I got it.

**Comment by cloudrac3r** [comment]
Your changes were applied a few hours ago in this commit: https://github.com/cloudrac3r/bibliogram/commit/ae130021958cdb5bf21b4f6c913c4ede2f47ad33

**Pull request closed without merging**
