### PR TITLE
Add Turkish Lang

### PR DESCRIPTION
**Pull request by ahmetcadirci25**

### CODE REVIEW

**Comment by cloudrac3r** [comment]
Thank you! To complete this patch, I just need to know one more thing: What's the word for Turkish in Turkish? This is so I can display it in the drop down menu on the settings page.

**Comment by cloudrac3r** [comment]
I'll assume the answer is `Türk`, provided by G-Translate, and merge this.

**Comment by llacb47** [comment]
That's the word for a turkish person, the language is `Türkçe`.

**Comment by cloudrac3r** [comment]
Thank you so much for the translation! The patch has been applied on Sourcehut, and you can see it here: https://git.sr.ht/~cadence/bibliogram/commit/dcd593e88528f16546dab95e93ca863284ccd01e

This won't show as merged on GitHub, but trust me, it's in the code.

**Pull request closed without merging**
