### PR TITLE
Create Persian Translation

### PR DESCRIPTION
**Pull request by KevinScruff**

### CODE REVIEW

**Comment by cloudrac3r** [comment]
Thank you so much! GitHub is not the upstream of Bibliogram, so I'll have to close this pull request and manually combine your changes into the repo, rather than merging it the normal way.

bibliogram.art is currently experiencing technical issues so you may not be able to see your results right away.

If you want to change anything past this point, please open a new pull request.

There are still more pages on Bibliogram that need to be adapted for translations, most notably the settings page. Is it okay to contact you in the future if there are more strings available for you to translate?

**Comment by cloudrac3r** [comment]
Oh - you'll need to tell me what the language label in the settings menu should be. For example, French would be _français_, which is the French word for French. What's the Persian name of the Persian language?

**Comment by cloudrac3r** [comment]
From what I can tell online, I think it's فارسي. If this is incorrect, please let me know so I can change it.

**Comment by cloudrac3r** [comment]
Changes applied as 9e589b58608385812ecffefeb215dbf26816f167 - thank you. If you want to make changes in the future, please let me know.

**Comment by KevinScruff** [comment]
> From what I can tell online, I think it's فارسي. If this is incorrect, please let me know so I can change it.

yeah, that's right.

**Comment by KevinScruff** [comment]
> Oh - you'll need to tell me what the language label in the settings menu should be. For example, French would be _français_, which is the French word for French. What's the Persian name of the Persian language?

فارسی

**Comment by cloudrac3r** [comment]
Thank you again. Bibliogram is often updated, and new feature often add text that needs to be translated. If you'd like to be notified when there are new things available for you to translate, please subscribe to this mailing list: https://lists.sr.ht/~cadence/bibliogram-translate . When new things are available to translate, I will make a descriptive post on that list showing what's new so that you can translate it.

If you're interested in keeping this translation up to date, please subscribe.

**Comment by KevinScruff** [comment]
ok, sure.

**Comment by cloudrac3r** [comment]
Thank you so much!

**Pull request closed without merging**
