### PR TITLE
Dark theme colors in css

### PR DESCRIPTION
**Pull request by mendel5**
As mentioned in https://github.com/cloudrac3r/bibliogram/issues/27 this is my proposal for the Bibliogram dark theme. It is not completely final yet so I am open for feedback.

Colors used:
* [#606060](https://www.color-hex.com/color/606060) for main background color
* [#252525](https://www.color-hex.com/color/252525) for profile overview background color
* [#ebebeb](https://www.color-hex.com/color/ebebeb) for font color
* [#ffffff](https://www.color-hex.com/color/ffffff) for font color 2
* [#ff9d9d](https://www.color-hex.com/color/ff9d9d) for link color

### CODE REVIEW

**Comment by cloudrac3r** [comment]
I'm swamped with work at the moment, so I've marked this notification as unread and I'll get to it at an unknown point in the future when I have time. Please be patient.

**Comment by cloudrac3r** [comment]
It's a start. I'm going to move out all of the simple style customisations like colours, widths, and gradients to another file so that they can be easily modified all in one place, which should make it easier for you to theme things.

**Comment by cloudrac3r** [comment]
I've refactored the sass files. Look at the new directory structure and create the dark theme the same way that I created the blue theme. All the colours are in one place for you to modify. You'll probably need to scrap this pull request and create a new one based off my new commits.

**Comment by cloudrac3r** [comment]
I have created a wiki page that you may find informative. https://github.com/cloudrac3r/bibliogram/wiki/Creating-themes

**Comment by mendel5** [comment]
Thank you, I will have a look!

**Comment by MrHeating** [comment]
Can we please have a #000 black background?

**Comment by cloudrac3r** [comment]
Closing due to inactivity. If you still want to complete this, please re-open the pull request, I'm excited to see what you come up with!

**Pull request closed without merging**
